// =============================================================================
// components/RideDetails/styles.ts — Ride Details Screen Styles
// =============================================================================

import { StyleSheet, Platform, StatusBar } from 'react-native';

const STATUS_BAR_H = Platform.OS === 'android' ? (StatusBar.currentHeight ?? 28) : 0;

export const ds = StyleSheet.create({
    // ─── Root ──────────────────────────────────────────────────────────────────
    root: { flex: 1, backgroundColor: '#F5F0EB' },
    scrollContent: { paddingBottom: 120 },

    // ─── Header ────────────────────────────────────────────────────────────────
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: STATUS_BAR_H + 12,
        paddingBottom: 14,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 1 },
    },
    backBtn: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: '#F5F0EB',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    headerTitle: {
        flex: 1,
        fontSize: 17,
        fontWeight: '700',
        color: '#1E1610',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#6B5344',
        marginTop: 1,
    },

    // ─── Loading / Error ───────────────────────────────────────────────────────
    centerContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
        gap: 12,
    },
    errorTitle: { fontSize: 18, fontWeight: '700', color: '#6B5344', marginTop: 12 },
    errorSub: { fontSize: 13, color: '#A8937F', textAlign: 'center', lineHeight: 19 },
    retryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 16,
        backgroundColor: '#FEF0E4',
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#FCDCBF',
    },
    retryBtnText: { fontSize: 13, fontWeight: '700', color: '#C24E00' },

    // ─── Driver Info Card ──────────────────────────────────────────────────────
    card: {
        marginHorizontal: 16,
        marginTop: 16,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    driverRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    driverAvatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#C24E00',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2.5,
    },
    driverInitials: {
        fontSize: 18,
        fontWeight: '800',
        color: '#fff',
        letterSpacing: 0.5,
    },
    driverInfo: { flex: 1 },
    driverName: { fontSize: 16, fontWeight: '700', color: '#1E1610' },
    driverMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 3,
    },
    driverTrustText: { fontSize: 12, fontWeight: '700' },
    driverMetaDot: {
        width: 3,
        height: 3,
        borderRadius: 1.5,
        backgroundColor: '#EAE0D8',
        marginHorizontal: 2,
    },
    driverVehicleText: { fontSize: 12, color: '#6B5344', textTransform: 'capitalize' },
    driverEmail: { fontSize: 11, color: '#A8937F', marginTop: 2 },

    // ─── Route Timeline ────────────────────────────────────────────────────────
    routeCard: {
        marginHorizontal: 16,
        marginTop: 12,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    routeRow: {
        flexDirection: 'row',
        gap: 14,
    },
    routeTimeline: {
        alignItems: 'center',
        paddingTop: 4,
        width: 18,
    },
    originDot: {
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#1E1610',
        borderWidth: 3,
        borderColor: '#1E1610',
    },
    routeLine: {
        width: 2,
        flex: 1,
        backgroundColor: '#EAE0D8',
        marginVertical: 4,
    },
    destDot: {
        width: 14,
        height: 14,
        borderRadius: 4,
        backgroundColor: '#C24E00',
    },
    routeDetails: { flex: 1 },
    routeLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A8937F',
        letterSpacing: 0.6,
        marginBottom: 2,
    },
    routeCity: { fontSize: 16, fontWeight: '700', color: '#1E1610' },
    routeDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginVertical: 14,
        paddingVertical: 8,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#F5F0EB',
    },
    routeDistText: { fontSize: 12, fontWeight: '600', color: '#6B5344' },
    routeDestLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A8937F',
        letterSpacing: 0.6,
        marginBottom: 2,
    },

    // ─── Departure Time Row ───────────────────────────────────────────────────
    departureRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 14,
        backgroundColor: '#FEF0E4',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    departureText: { fontSize: 14, fontWeight: '700', color: '#C24E00' },
    departureDate: { fontSize: 12, color: '#A33D00' },

    // ─── Price Breakdown ──────────────────────────────────────────────────────
    priceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    priceLabel: { fontSize: 13, color: '#6B5344' },
    priceValue: { fontSize: 14, fontWeight: '600', color: '#1E1610' },
    priceDivider: {
        height: 1,
        backgroundColor: '#EAE0D8',
        marginVertical: 8,
    },
    priceTotalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    priceTotalLabel: { fontSize: 15, fontWeight: '700', color: '#1E1610' },
    priceTotalValue: { fontSize: 20, fontWeight: '800', color: '#C24E00' },
    pricePerSeatNote: {
        fontSize: 11,
        color: '#A8937F',
        textAlign: 'right',
        marginTop: 2,
    },

    // ─── Badges ────────────────────────────────────────────────────────────────
    badgeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginHorizontal: 16,
        marginTop: 12,
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 20,
        borderWidth: 1,
    },
    badgeText: { fontSize: 12, fontWeight: '600' },

    emergencyBadge: { backgroundColor: '#fffbeb', borderColor: '#fde68a' },
    emergencyText: { color: '#f59e0b' },

    womenBadge: { backgroundColor: '#fce7f3', borderColor: '#f9a8d4' },
    womenText: { color: '#db2777' },

    instantBadge: { backgroundColor: '#ecfdf5', borderColor: '#a7f3d0' },
    instantText: { color: '#059669' },

    seatBadge: { backgroundColor: '#e3f2fd', borderColor: '#90caf9' },
    seatText: { color: '#1976d2' },

    fuelBadge: { backgroundColor: '#F5F0EB', borderColor: '#EAE0D8' },
    fuelText: { color: '#6B5344' },

    // ─── Seat Selector ─────────────────────────────────────────────────────────
    seatSelectorCard: {
        marginHorizontal: 16,
        marginTop: 12,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    seatSelectorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    seatSelectorLabel: { fontSize: 14, fontWeight: '600', color: '#1E1610' },
    seatSelectorSub: { fontSize: 11, color: '#A8937F', marginTop: 2 },
    seatStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: '#F5F0EB',
        borderRadius: 24,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    seatStepperBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 1,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
    },
    seatStepperBtnDisabled: {
        backgroundColor: '#F5F0EB',
        elevation: 0,
        shadowOpacity: 0,
    },
    seatStepperValue: { fontSize: 18, fontWeight: '800', color: '#1E1610', minWidth: 20, textAlign: 'center' },

    // ─── Bottom Book Button ────────────────────────────────────────────────────
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#EAE0D8',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: Platform.OS === 'ios' ? 30 : 16,
        elevation: 12,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: -4 },
    },
    bottomBarRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    bottomPriceCol: { flex: 1 },
    bottomPriceLabel: { fontSize: 11, color: '#6B5344' },
    bottomPriceValue: { fontSize: 22, fontWeight: '800', color: '#C24E00' },
    bookBtn: {
        flex: 1.5,
        height: 52,
        borderRadius: 16,
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        elevation: 4,
        shadowColor: '#C24E00',
        shadowOpacity: 0.35,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    bookBtnDisabled: {
        backgroundColor: '#EAE0D8',
        shadowOpacity: 0,
        elevation: 0,
    },
    bookBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },

    // ─── Booking Success ──────────────────────────────────────────────────────
    successRoot: { flex: 1, backgroundColor: '#fff' },
    successScroll: { flex: 1 },
    successContent: { paddingBottom: 40 },
    successTop: {
        alignItems: 'center',
        paddingTop: STATUS_BAR_H + 40,
        paddingBottom: 24,
        paddingHorizontal: 24,
    },
    successIconWrap: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#FEF0E4',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        borderWidth: 3,
        borderColor: '#FCDCBF',
    },
    successTitle: { fontSize: 24, fontWeight: '800', color: '#1E1610', textAlign: 'center' },
    successSub: { fontSize: 14, color: '#6B5344', marginTop: 6, textAlign: 'center' },

    successCard: {
        marginHorizontal: 16,
        backgroundColor: '#FAF7F4',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    successSectionTitle: { fontSize: 12, fontWeight: '700', color: '#A8937F', letterSpacing: 0.5, marginBottom: 10 },
    successRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    successLabel: { fontSize: 13, color: '#6B5344' },
    successValue: { fontSize: 14, fontWeight: '600', color: '#1E1610' },
    successPriceValue: { fontSize: 18, fontWeight: '800', color: '#C24E00' },

    // ─── Handoff Buttons ──────────────────────────────────────────────────────
    handoffCard: {
        marginHorizontal: 16,
        marginTop: 16,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    handoffTitle: { fontSize: 12, fontWeight: '700', color: '#A8937F', letterSpacing: 0.5, marginBottom: 12 },
    handoffBtnRow: { flexDirection: 'row', gap: 10 },
    handoffBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1.5,
    },
    whatsappBtn: {
        backgroundColor: '#FEF0E4',
        borderColor: '#C24E00',
    },
    whatsappBtnText: { fontSize: 14, fontWeight: '700', color: '#C24E00' },
    callBtn: {
        backgroundColor: '#FEF0E4',
        borderColor: '#C24E00',
    },
    callBtnText: { fontSize: 14, fontWeight: '700', color: '#C24E00' },
    handoffFallback: { fontSize: 13, color: '#A8937F', textAlign: 'center', lineHeight: 19 },

    doneBtn: {
        marginHorizontal: 16,
        marginTop: 20,
        height: 52,
        borderRadius: 16,
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        elevation: 4,
        shadowColor: '#C24E00',
        shadowOpacity: 0.35,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    doneBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },

    // ─── Edit Ride Buttons ────────────────────────────────────────────────────
    editBtnGroup: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    editBtn: {
        flex: 1,
        height: 52,
        borderRadius: 16,
        backgroundColor: '#F5F0EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    editBtnText: { color: '#3D2F22', fontSize: 15, fontWeight: '700' },

    cancelRideBtn: {
        flex: 1,
        height: 52,
        borderRadius: 16,
        backgroundColor: '#fee2e2',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        borderWidth: 1,
        borderColor: '#fca5a5',
    },
    cancelRideBtnText: { color: '#ef4444', fontSize: 15, fontWeight: '700' },

    // ─── Modal ────────────────────────────────────────────────────────────────
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        paddingTop: 20,
        paddingHorizontal: 20,
        paddingBottom: Platform.OS === 'ios' ? 34 : 16,
        maxHeight: '90%',
        elevation: 16,
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: -4 },
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1E1610',
    },
    modalCloseBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F5F0EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalFieldWrap: {
        marginBottom: 20,
    },
    modalFieldLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#3D2F22',
        marginBottom: 8,
    },
    modalInputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FAF7F4',
        borderWidth: 1,
        borderColor: '#EAE0D8',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    modalSwitchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 4,
    },
    modalSwitchLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1E1610',
    },
    modalSwitchSub: {
        fontSize: 12,
        color: '#6B5344',
        marginTop: 2,
    },
    modalSaveBtn: {
        marginTop: 10,
        marginBottom: 0,
        height: 54,
        borderRadius: 16,
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    modalSaveBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
});
