// =============================================================================
// components/RideDetails/styles.ts — Ride Details Screen Styles
// =============================================================================

import { StyleSheet, Platform, StatusBar } from 'react-native';
import { sp, fs, wp, hp } from '@/constants/responsive';

const STATUS_BAR_H = Platform.OS === 'android' ? (StatusBar.currentHeight ?? 28) : 0;

export const ds = StyleSheet.create({
    // ─── Root ──────────────────────────────────────────────────────────────────
    root: { flex: 1, backgroundColor: '#F5F0EB' },
    scrollContent: { paddingBottom: hp(120) },

    // ─── Header ────────────────────────────────────────────────────────────────
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: STATUS_BAR_H + hp(12),
        paddingBottom: hp(14),
        paddingHorizontal: wp(16),
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: sp(4),
        shadowOffset: { width: 0, height: 1 },
    },
    backBtn: {
        width: sp(38),
        height: sp(38),
        borderRadius: sp(19),
        backgroundColor: '#F5F0EB',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: wp(12),
    },
    headerTitle: {
        flex: 1,
        fontSize: fs(17),
        fontWeight: '700',
        color: '#1E1610',
    },
    headerSubtitle: {
        fontSize: fs(12),
        color: '#6B5344',
        marginTop: hp(1),
    },

    // ─── Loading / Error ───────────────────────────────────────────────────────
    centerContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: wp(32),
        gap: sp(12),
    },
    errorTitle: { fontSize: fs(18), fontWeight: '700', color: '#6B5344', marginTop: hp(12) },
    errorSub: { fontSize: fs(13), color: '#A8937F', textAlign: 'center', lineHeight: fs(19) },
    retryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(6),
        marginTop: hp(16),
        backgroundColor: '#FEF0E4',
        paddingHorizontal: wp(18),
        paddingVertical: hp(10),
        borderRadius: sp(20),
        borderWidth: 1,
        borderColor: '#FCDCBF',
    },
    retryBtnText: { fontSize: fs(13), fontWeight: '700', color: '#C24E00' },

    // ─── Driver Info Card ──────────────────────────────────────────────────────
    card: {
        marginHorizontal: wp(16),
        marginTop: hp(16),
        backgroundColor: '#fff',
        borderRadius: sp(16),
        padding: sp(16),
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: sp(6),
        shadowOffset: { width: 0, height: 2 },
    },
    driverRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(12),
    },
    driverAvatar: {
        width: sp(52),
        height: sp(52),
        borderRadius: sp(26),
        backgroundColor: '#C24E00',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: sp(2.5),
    },
    driverInitials: {
        fontSize: fs(18),
        fontWeight: '800',
        color: '#fff',
        letterSpacing: 0.5,
    },
    driverInfo: { flex: 1 },
    driverName: { fontSize: fs(16), fontWeight: '700', color: '#1E1610' },
    driverMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(4),
        marginTop: hp(3),
    },
    driverTrustText: { fontSize: fs(12), fontWeight: '700' },
    driverMetaDot: {
        width: sp(3),
        height: sp(3),
        borderRadius: sp(1.5),
        backgroundColor: '#EAE0D8',
        marginHorizontal: wp(2),
    },
    driverVehicleText: { fontSize: fs(12), color: '#6B5344', textTransform: 'capitalize' },
    driverEmail: { fontSize: fs(11), color: '#A8937F', marginTop: hp(2) },

    // ─── Route Timeline ────────────────────────────────────────────────────────
    routeCard: {
        marginHorizontal: wp(16),
        marginTop: hp(12),
        backgroundColor: '#fff',
        borderRadius: sp(16),
        padding: sp(16),
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: sp(6),
        shadowOffset: { width: 0, height: 2 },
    },
    routeRow: {
        flexDirection: 'row',
        gap: sp(14),
    },
    routeTimeline: {
        alignItems: 'center',
        paddingTop: hp(4),
        width: sp(18),
    },
    originDot: {
        width: sp(14),
        height: sp(14),
        borderRadius: sp(7),
        backgroundColor: '#1E1610',
        borderWidth: sp(3),
        borderColor: '#1E1610',
    },
    routeLine: {
        width: sp(2),
        flex: 1,
        backgroundColor: '#EAE0D8',
        marginVertical: hp(4),
    },
    destDot: {
        width: sp(14),
        height: sp(14),
        borderRadius: sp(4),
        backgroundColor: '#C24E00',
    },
    routeDetails: { flex: 1 },
    routeLabel: {
        fontSize: fs(10),
        fontWeight: '700',
        color: '#A8937F',
        letterSpacing: 0.6,
        marginBottom: hp(2),
    },
    routeCity: { fontSize: fs(16), fontWeight: '700', color: '#1E1610' },
    routeDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(8),
        marginVertical: hp(14),
        paddingVertical: hp(8),
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#F5F0EB',
    },
    routeDistText: { fontSize: fs(12), fontWeight: '600', color: '#6B5344' },
    routeDestLabel: {
        fontSize: fs(10),
        fontWeight: '700',
        color: '#A8937F',
        letterSpacing: 0.6,
        marginBottom: hp(2),
    },

    // ─── Departure Time Row ───────────────────────────────────────────────────
    departureRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(8),
        marginTop: hp(14),
        backgroundColor: '#FEF0E4',
        borderRadius: sp(12),
        paddingHorizontal: wp(14),
        paddingVertical: hp(10),
    },
    departureText: { fontSize: fs(14), fontWeight: '700', color: '#C24E00' },
    departureDate: { fontSize: fs(12), color: '#A33D00' },

    // ─── Price Breakdown ──────────────────────────────────────────────────────
    priceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: hp(8),
    },
    priceLabel: { fontSize: fs(13), color: '#6B5344' },
    priceValue: { fontSize: fs(14), fontWeight: '600', color: '#1E1610' },
    priceDivider: {
        height: 1,
        backgroundColor: '#EAE0D8',
        marginVertical: hp(8),
    },
    priceTotalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    priceTotalLabel: { fontSize: fs(15), fontWeight: '700', color: '#1E1610' },
    priceTotalValue: { fontSize: fs(20), fontWeight: '800', color: '#C24E00' },
    pricePerSeatNote: {
        fontSize: fs(11),
        color: '#A8937F',
        textAlign: 'right',
        marginTop: hp(2),
    },

    // ─── Badges ────────────────────────────────────────────────────────────────
    badgeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: sp(8),
        marginHorizontal: wp(16),
        marginTop: hp(12),
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(5),
        paddingHorizontal: wp(12),
        paddingVertical: hp(7),
        borderRadius: sp(20),
        borderWidth: 1,
    },
    badgeText: { fontSize: fs(12), fontWeight: '600' },

    emergencyBadge: { backgroundColor: '#FEFDF2', borderColor: '#D4960F' },
    emergencyText: { color: '#D4960F' },

    womenBadge: { backgroundColor: '#FEF0E4', borderColor: '#C24E00' },
    womenText: { color: '#C24E00' },

    instantBadge: { backgroundColor: '#F2FAF5', borderColor: '#3DAA6E' },
    instantText: { color: '#3DAA6E' },

    seatBadge: { backgroundColor: '#e3f2fd', borderColor: '#90caf9' },
    seatText: { color: '#1976d2' },

    fuelBadge: { backgroundColor: '#e3f2fd', borderColor: '#90caf9' },
    fuelText: { color: '#1976d2' },

    // ─── Seat Selector ─────────────────────────────────────────────────────────
    seatSelectorCard: {
        marginHorizontal: wp(16),
        marginTop: hp(12),
        backgroundColor: '#fff',
        borderRadius: sp(16),
        padding: sp(16),
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: sp(6),
        shadowOffset: { width: 0, height: 2 },
    },
    seatSelectorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    seatSelectorLabel: { fontSize: fs(14), fontWeight: '600', color: '#1E1610' },
    seatSelectorSub: { fontSize: fs(11), color: '#A8937F', marginTop: hp(2) },
    seatStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(12),
        backgroundColor: '#F5F0EB',
        borderRadius: sp(24),
        paddingHorizontal: wp(8),
        paddingVertical: hp(4),
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    seatStepperBtn: {
        width: sp(32),
        height: sp(32),
        borderRadius: sp(16),
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 1,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: sp(2),
        shadowOffset: { width: 0, height: 1 },
    },
    seatStepperBtnDisabled: {
        backgroundColor: '#F5F0EB',
        elevation: 0,
        shadowOpacity: 0,
    },
    seatStepperValue: { fontSize: fs(18), fontWeight: '800', color: '#1E1610', minWidth: sp(20), textAlign: 'center' },

    // ─── Bottom Book Button ────────────────────────────────────────────────────
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#EAE0D8',
        paddingHorizontal: wp(16),
        paddingTop: hp(12),
        paddingBottom: Platform.OS === 'ios' ? hp(30) : hp(16),
        elevation: 12,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: sp(8),
        shadowOffset: { width: 0, height: -4 },
    },
    bottomBarRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: sp(14),
    },
    bottomPriceCol: { flex: 1 },
    bottomPriceLabel: { fontSize: fs(11), color: '#6B5344' },
    bottomPriceValue: { fontSize: fs(22), fontWeight: '800', color: '#C24E00' },
    bookBtn: {
        flex: 1.5,
        height: sp(52),
        borderRadius: sp(16),
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(8),
        elevation: 4,
        shadowColor: '#C24E00',
        shadowOpacity: 0.35,
        shadowRadius: sp(8),
        shadowOffset: { width: 0, height: 4 },
    },
    bookBtnDisabled: {
        backgroundColor: '#EAE0D8',
        shadowOpacity: 0,
        elevation: 0,
    },
    bookBtnText: { color: '#fff', fontSize: fs(16), fontWeight: '800' },

    // ─── Booking Success ──────────────────────────────────────────────────────
    successRoot: { flex: 1, backgroundColor: '#fff' },
    successScroll: { flex: 1 },
    successContent: { paddingBottom: hp(40) },
    successTop: {
        alignItems: 'center',
        paddingTop: STATUS_BAR_H + hp(40),
        paddingBottom: hp(24),
        paddingHorizontal: wp(24),
    },
    successIconWrap: {
        width: sp(80),
        height: sp(80),
        borderRadius: sp(40),
        backgroundColor: '#FEF0E4',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: hp(16),
        borderWidth: sp(3),
        borderColor: '#FCDCBF',
    },
    successTitle: { fontSize: fs(24), fontWeight: '800', color: '#1E1610', textAlign: 'center' },
    successSub: { fontSize: fs(14), color: '#6B5344', marginTop: hp(6), textAlign: 'center' },

    successCard: {
        marginHorizontal: wp(16),
        backgroundColor: '#FAF7F4',
        borderRadius: sp(16),
        padding: sp(16),
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    successSectionTitle: { fontSize: fs(12), fontWeight: '700', color: '#A8937F', letterSpacing: 0.5, marginBottom: hp(10) },
    successRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: hp(8),
    },
    successLabel: { fontSize: fs(13), color: '#6B5344' },
    successValue: { fontSize: fs(14), fontWeight: '600', color: '#1E1610' },
    successPriceValue: { fontSize: fs(18), fontWeight: '800', color: '#C24E00' },

    // ─── Handoff Buttons ──────────────────────────────────────────────────────
    handoffCard: {
        marginHorizontal: wp(16),
        marginTop: hp(16),
        backgroundColor: '#fff',
        borderRadius: sp(16),
        padding: sp(16),
        borderWidth: 1,
        borderColor: '#EAE0D8',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: sp(6),
        shadowOffset: { width: 0, height: 2 },
    },
    handoffTitle: { fontSize: fs(12), fontWeight: '700', color: '#A8937F', letterSpacing: 0.5, marginBottom: hp(12) },
    handoffBtnRow: { flexDirection: 'row', gap: sp(10) },
    handoffBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(8),
        paddingVertical: hp(14),
        borderRadius: sp(14),
        borderWidth: sp(1.5),
    },
    whatsappBtn: {
        backgroundColor: '#FEF0E4',
        borderColor: '#C24E00',
    },
    whatsappBtnText: { fontSize: fs(14), fontWeight: '700', color: '#C24E00' },
    callBtn: {
        backgroundColor: '#FEF0E4',
        borderColor: '#C24E00',
    },
    callBtnText: { fontSize: fs(14), fontWeight: '700', color: '#C24E00' },
    handoffFallback: { fontSize: fs(13), color: '#A8937F', textAlign: 'center', lineHeight: fs(19) },

    doneBtn: {
        marginHorizontal: wp(16),
        marginTop: hp(20),
        height: sp(52),
        borderRadius: sp(16),
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(8),
        elevation: 4,
        shadowColor: '#C24E00',
        shadowOpacity: 0.35,
        shadowRadius: sp(8),
        shadowOffset: { width: 0, height: 4 },
    },
    doneBtnText: { color: '#fff', fontSize: fs(16), fontWeight: '800' },

    // ─── Edit Ride Buttons ────────────────────────────────────────────────────
    editBtnGroup: {
        flexDirection: 'row',
        gap: sp(12),
        width: '100%',
    },
    editBtn: {
        flex: 1,
        height: sp(52),
        borderRadius: sp(16),
        backgroundColor: '#F5F0EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(6),
        borderWidth: 1,
        borderColor: '#EAE0D8',
    },
    editBtnText: { color: '#3D2F22', fontSize: fs(15), fontWeight: '700' },

    cancelRideBtn: {
        flex: 1,
        height: sp(52),
        borderRadius: sp(16),
        backgroundColor: '#FFF6F5',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(6),
        borderWidth: 1,
        borderColor: '#FCDCBF',
    },
    cancelRideBtnText: { color: '#D9622A', fontSize: fs(15), fontWeight: '700' },

    // ─── Modal ────────────────────────────────────────────────────────────────
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: sp(24),
        borderTopRightRadius: sp(24),
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        paddingTop: hp(20),
        paddingHorizontal: wp(20),
        paddingBottom: Platform.OS === 'ios' ? hp(34) : hp(16),
        maxHeight: '90%',
        elevation: 16,
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: sp(12),
        shadowOffset: { width: 0, height: -4 },
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: hp(20),
    },
    modalTitle: {
        fontSize: fs(20),
        fontWeight: '800',
        color: '#1E1610',
    },
    modalCloseBtn: {
        width: sp(32),
        height: sp(32),
        borderRadius: sp(16),
        backgroundColor: '#F5F0EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalFieldWrap: {
        marginBottom: hp(20),
    },
    modalFieldLabel: {
        fontSize: fs(14),
        fontWeight: '700',
        color: '#3D2F22',
        marginBottom: hp(8),
    },
    modalInputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FAF7F4',
        borderWidth: 1,
        borderColor: '#EAE0D8',
        borderRadius: sp(12),
        paddingHorizontal: wp(12),
        paddingVertical: hp(12),
    },
    modalSwitchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: hp(4),
    },
    modalSwitchLabel: {
        fontSize: fs(15),
        fontWeight: '600',
        color: '#1E1610',
    },
    modalSwitchSub: {
        fontSize: fs(12),
        color: '#6B5344',
        marginTop: hp(2),
    },
    modalSaveBtn: {
        marginTop: hp(10),
        marginBottom: 0,
        height: sp(54),
        borderRadius: sp(16),
        backgroundColor: '#C24E00',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: sp(8),
    },
    modalSaveBtnText: { color: '#fff', fontSize: fs(16), fontWeight: '800' },
});
